clearglass:
  enableDevUsers: false

smtp:
  host: mailmock
  port: 8025
  tls: false
  starttls: false
  username: ""
  password: ""

image:
  registry: registry.gitlab.com/clearglass/clearglass-community
  tag: master
  pullPolicy: Always
  secrets:
    - name: gitlab-registry

http:
  host: localhost
  tlsSecret: ''
