MIST_HOST: localhost
smtp:
  host: smtp.sendgrid.net
  port: 2525
  tls: "False"
  starttls: "True"
  username: apikey
  password: ""

image:
  registry: registry.gitlab.com/clearglass/clearglass-community
  tag: master
  pullPolicy: Always
  secrets:
    - name: gitlab-registry
