stages:
  - build
  - deploy
  - undeploy

build nginx:
  stage: build
  image: docker:git
  services:
  - docker:dind
  variables:
    DOCKER_DRIVER: overlay2
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  script:
    - docker build -t $CI_REGISTRY_IMAGE/nginx:$CI_COMMIT_REF_SLUG .
    - docker push $CI_REGISTRY_IMAGE/nginx:$CI_COMMIT_REF_SLUG

deploy:
  stage: deploy
  image: dtzar/helm-kubectl
  environment:
    name: review/$CI_COMMIT_REF_NAME
    url: http://$CI_COMMIT_REF_SLUG.community.env.clear.glass
    on_stop: undeploy
  script:
    - export name="$CI_PROJECT_PATH_SLUG-$CI_COMMIT_REF_SLUG"
    - |
        helm upgrade --install --namespace "$name" \
          --set COMMIT_SLUG=$CI_COMMIT_REF_SLUG \
          --set MIST_HOST=$CI_COMMIT_REF_SLUG.community.env.clear.glass \
          --set SMTP_PASSWORD=$SMTP_PASSWORD \
          "$name" ./chart/

undeploy:
  stage: undeploy
  image: dtzar/helm-kubectl
  variables:
    GIT_STRATEGY: none
  environment:
    name: review/$CI_COMMIT_REF_NAME
    action: stop
  script:
    - export name="$CI_PROJECT_PATH_SLUG-$CI_COMMIT_REF_SLUG"
    - helm delete --purge "$name"
  when: manual
  allow_failure: true
