stages:
  - build
  - deploy
  - undeploy

build nginx:
  stage: build
  image: docker:git
  services:
  - docker:dind
  variables:
    DOCKER_DRIVER: overlay2
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  script:
    - docker build -t $CI_REGISTRY_IMAGE/nginx:$CI_COMMIT_REF_SLUG .
    - docker push $CI_REGISTRY_IMAGE/nginx:$CI_COMMIT_REF_SLUG

deploy:
  stage: deploy
  image: dtzar/helm-kubectl
  environment:
    name: review/$CI_COMMIT_REF_NAME
    url: http://$CI_PROJECT_PATH_SLUG-$CI_ENVIRONMENT_SLUG.$AUTO_DEVOPS_DOMAIN
    on_stop: undeploy
  script:
    - export name="$CI_PROJECT_PATH_SLUG-$CI_COMMIT_REF_SLUG"
    - helm upgrade --install --namespace "$name" --set COMMIT_SLUG=$CI_COMMIT_REF_SLUG "$name" ./chart/

undeploy:
  stage: undeploy
  image: dtzar/helm-kubectl
  variables:
    GIT_STRATEGY: none
  environment:
    name: review/$CI_COMMIT_REF_NAME
    action: stop
  script:
    - export name="$CI_PROJECT_PATH_SLUG-$CI_COMMIT_REF_SLUG"
    - helm delete "$name"
  when: manual
  allow_failure: true
