version: '2.0'
services:
  beringei:
    image: gcr.io/mist-ops/beringei:plain
    command: "./beringei/service/beringei_main -beringei_configuration_path /etc/beringei/beringei.json -create_directories -sleep_between_bucket_finalization_secs 60 -allowed_timestamp_behind 300 -bucket_size 600 -buckets 144 -logtostderr -v=2"
    hostname: beringei
    ports:
      - 9999:9999
    volumes:
      - ./docker/beringei:/etc/beringei
  beringei-http:
    image: gcr.io/mist-ops/beringei:plain
    command: ./beringei/tools/plain_text_service/beringei_plain_text_service -beringei_configuration_path /etc/beringei/beringei.json -ip 0.0.0.0 -http_port 9990
    ports:
      - 9990:9990
    volumes:
      - ./docker/beringei:/etc/beringei
    depends_on:
      - beringei
  gocky:
    depends_on:
      - beringei
      - beringei-http
