apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    clearglass.service: beat
  name: beat
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        clearglass.service: beat
    spec:
      imagePullSecrets:
{{ toYaml .Values.image.secrets | indent 8 }}
      containers:
      - args:
        - bin/wait-all
        - bin/beat
        image: {{ .Values.image.registry }}/api:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: beat
        resources:
          resources:
            limits:
              memory: 1024Mi
              cpu: 200m
            requests:
              memory: 200Mi
              cpu: 50m
        volumeMounts:
        - name: clearglass-config
          mountPath: /etc/clearglass/settings.py
          subPath: settings.py
      volumes:
      - name: clearglass-config
        configMap:
          name: clearglass-configmap
