apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    clearglass.service: celery-gevent
  name: celery-gevent
spec:
  replicas: 1
  template:
    metadata:
      labels:
        clearglass.service: celery-gevent
    spec:
      imagePullSecrets:
{{ toYaml .Values.image.secrets | indent 8 }}
      containers:
      - args:
        - bin/wait-all
        - bin/celery-gevent
        image: {{ .Values.image.registry }}/api:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: celery-gevent
        resources:
          requests:
            memory: 150Mi
            cpu: 60m
          limits:
            memory: 1000Mi
            cpu: 1000m
        volumeMounts:
        - name: clearglass-config
          mountPath: /etc/clearglass/settings/settings.py
          subPath: settings.py
      volumes:
      - name: clearglass-config
        configMap:
          name: clearglass-configmap
