apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    clearglass.service: clearglass-elasticsearch
  name: clearglass-elasticsearch
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
