apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    clearglass.service: clearglass-mongodb
  name: clearglass-mongodb
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
