apiVersion: v1
kind: ConfigMap
metadata:
  name: clearglass-configmap
data:
  settings.py: |
    CORE_URI = "http{{ if .Values.http.tlsSecret }}s{{end}}://{{ .Values.http.host }}"
    JS_BUILD = False
    ENABLE_DEV_USERS = True
