apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    clearglass.service: elasticsearch
  name: elasticsearch
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        clearglass.service: elasticsearch
    spec:
      containers:
      - image: elasticsearch:5.5.2
        name: elasticsearch
        resources:
          requests:
            memory: 2500Mi
            cpu: 50m
          limits:
            memory: 4000Mi
            cpu: 2000m
        volumeMounts:
        - mountPath: /usr/share/elasticsearch/data
          name: clearglass-elasticsearch
      volumes:
      - name: clearglass-elasticsearch
        persistentVolumeClaim:
          claimName: clearglass-elasticsearch
