apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    clearglass.service: hubshell
  name: hubshell
spec:
  replicas: 1
  template:
    metadata:
      labels:
        clearglass.service: hubshell
    spec:
      imagePullSecrets:
{{ toYaml .Values.image.secrets | indent 8 }}
      containers:
      - args:
        - bin/wait-all
        - bin/hubshell
        image: {{ .Values.image.registry }}/api:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: hubshell
        resources:
          requests:
            memory: 80Mi
            cpu: 10m
          limits:
            memory: 200Mi
            cpu: 1000m
        volumeMounts:
        - name: clearglass-config
          mountPath: /etc/clearglass/settings.py
          subPath: settings.py
      volumes:
      - name: clearglass-config
        configMap:
          name: clearglass-configmap
