apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: influxdb
  labels:
    clearglass.service: influxdb
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        clearglass.service: influxdb
    spec:
      containers:
        - name: influxdb
          image: influxdb
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: INFLUXDB_DB
              value: telegraf
          volumeMounts:
            - mountPath: /data/db
              name: influxdb-data
      volumes:
        - name: influxdb-data
          persistentVolumeClaim:
            claimName: influxdb
