apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb
  labels:
    clearglass.service: influxdb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
