apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    clearglass.service: logstash
  name: logstash
spec:
  replicas: 1
  template:
    metadata:
      labels:
        clearglass.service: logstash
    spec:
      containers:
      - image: mist/logstash:staging
        name: logstash
        resources:
          requests:
            memory: 500Mi
            cpu: 170m
          limits:
            memory: 1000Mi
            cpu: 1000m
