apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.8.0 (0c0c027)
  creationTimestamp: null
  labels:
    io.kompose.service: logstash
  name: logstash
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: logstash
    spec:
      containers:
      - image: mist/logstash:staging
        name: logstash
        resources:
          requests:
            memory: 500Mi
            cpu: 170m
          limits:
            memory: 1000Mi
            cpu: 1000m
      restartPolicy: Always
status: {}
