apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    clearglass.service: memcached
  name: memcached
spec:
  replicas: 1
  template:
    metadata:
      labels:
        clearglass.service: memcached
    spec:
      containers:
      - image: memcached
        name: memcached
        resources:
          requests:
            memory: 30Mi
            cpu: 1m
          limits:
            memory: 60Mi
            cpu: 100m
