apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    clearglass.service: mongodb
  name: mongodb
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        clearglass.service: mongodb
    spec:
      containers:
      - image: mongo:3.2
        name: mongodb
        resources:
          requests:
            memory: 100Mi
            cpu: 100m
          limits:
            memory: 200Mi
            cpu: 1000m
        volumeMounts:
        - mountPath: /data/db
          name: clearglass-mongodb
      volumes:
      - name: clearglass-mongodb
        persistentVolumeClaim:
          claimName: clearglass-mongodb
