apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.8.0 (0c0c027)
  creationTimestamp: null
  labels:
    io.kompose.service: mongodb
  name: mongodb
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: mongodb
    spec:
      containers:
      - image: mongo:3.2
        name: mongodb
        resources: {}
        volumeMounts:
        - mountPath: /data/db
          name: clearglass-mongodb
      restartPolicy: Always
      volumes:
      - name: clearglass-mongodb
        persistentVolumeClaim:
          claimName: clearglass-mongodb
status: {}
