apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.8.0 (0c0c027)
  creationTimestamp: null
  labels:
    io.kompose.service: nginx
  name: nginx
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: nginx
    spec:
      containers:
      - image:  registry.gitlab.com/clearglass/clearglass-community/nginx:{{ .Values.COMMIT_SLUG }}
        name: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-config
          mountPath: /opt
        command: ["nginx", "-c", "/opt/nginx.conf"]
      restartPolicy: Always
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-configmap
status: {}
