apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    clearglass.service: nginx
  name: nginx
spec:
  replicas: 1
  template:
    metadata:
      labels:
        clearglass.service: nginx
    spec:
      imagePullSecrets:
{{ toYaml .Values.image.secrets | indent 8 }}
      containers:
      - image: {{ .Values.image.registry }}/nginx:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
        resources:
          requests:
            memory: 30Mi
            cpu: 10m
          limits:
            memory: 60Mi
            cpu: 1000m
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-configmap
