apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    clearglass.service: rabbitmq
  name: rabbitmq
spec:
  replicas: 1
  template:
    metadata:
      labels:
        clearglass.service: rabbitmq
    spec:
      containers:
      - image: rabbitmq:3.6.6-management
        name: rabbitmq
        resources:
          requests:
            memory: 200Mi
            cpu: 100m
          limits:
            memory: 400Mi
            cpu: 1000m
