apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: traefik
  labels:
    clearglass.service: traefik
spec:
  replicas: 1
  template:
    metadata:
      labels:
        clearglass.service: traefik
    spec:
      containers:
        - name: traefik
          image: traefik:v1.4
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - --web
            - --logLevel=INFO
          ports:
            - containerPort: 80
            - containerPort: 8080
          resources:
            requests:
              memory: 35Mi
              cpu: 5m
            limits:
              memory: 100Mi
              cpu: 1000m
