apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    clearglass.service: ui
  name: ui
spec:
  replicas: 1
  template:
    metadata:
      labels:
        clearglass.service: ui
    spec:
      imagePullSecrets:
{{ toYaml .Values.image.secrets | indent 8 }}
      containers:
      - args:
        - sh
        - /entry.sh
        image: {{ .Values.image.registry }}/ui:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: ui
        resources:
          requests:
            memory: 20Mi
            cpu: 10m
          limits:
            memory: 40Mi
            cpu: 100m
