apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.8.0 (0c0c027)
  creationTimestamp: null
  labels:
    io.kompose.service: api
  name: api
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: api
    spec:
      containers:
      - args:
        - bin/wait-all
        - bin/uwsgi
        env:
        - name: DEFAULTS_FILE
          value: /etc/clearglass/defaults.py
        - name: SETTINGS_FILE
          value: /etc/clearglass/settings.py
        image: mist/mist:io-staging
        name: api
        resources: {}
        stdin: true
        tty: true
        volumeMounts:
        - mountPath: /etc/clearglass
          name: api-claim0
      restartPolicy: Always
      volumes:
      - name: api-claim0
        persistentVolumeClaim:
          claimName: api-claim0
status: {}
