apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.8.0 (0c0c027)
  creationTimestamp: null
  labels:
    io.kompose.service: nginx
  name: nginx
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: nginx
    spec:
      containers:
      - image: mist/nginx:staging
        name: nginx
        ports:
        - containerPort: 80
        resources:
          volumeMounts:
          - name: nginx-conf
            mountPath: /opt/nginx/
          command: ["nginx", "-c", "/opt/nginx/nginx.conf"]
      restartPolicy: Always
      volumes:
      - name: nginx-conf
        configMap:
          name: nginx-conf
status: {}
